version: "3.9"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - net-db
    environment:
      - MYSQL_USER=danang
      - MYSQL_ROOT_PASSWORD=danang
      - MYSQL_PASSWORD=danang 
      - MYSQL_DATABASE=todolist
    # volumes: 
    #   - ./ginmysql:/var/lib/mysql
    container_name: db-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - net-db
    ports:
      - "5002:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    # volumes:
    #   - ./sessionss
    container_name: db-phpmyadmin
networks:
  net-db: